---
# Configure Chrony service
#
- name: deploy chrony.conf template
  ansible.builtin.template:
   src: chrony.conf.j2
   dest: /etc/chrony.conf
   owner: root
   group: root
   mode: 0644
   backup: true

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted
