---
# Install Docker service
#
- name: update cache
  dnf:
    update_cache: yes

- name: Install Docker CE
  dnf:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Enable Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

